version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.6.9
    environment: 
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - 5672:5672

  mongo:
    image: mongo:3.4.4
    volumes:
      - /opt/mongodb:/data/db

  flask:
    build: .
    ports:
      - 5000:5000
    volumes: 
      - ./app:/opt/app
    depends_on:
      - mongo
      - rabbitmq
    entrypoint: 
      - python
      - app.py

  worker:
    build: .
    volumes:
      - ./app:/opt/app
    depends_on:
      - mongo
      - rabbitmq
    working_dir: /opt
    entrypoint:
      - celery 
      - "-A"
      - app
      - worker
      - "--loglevel=info"
